# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  black:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Check formatting with black
      run: |
        pip install black
        black --check bout_cartesian_convert.py
        black --check crystal_vis_script.py
        black --check gif_maker.py
        black --check jorek_vis_script.py
        black --check time_reader.py
        black --check xyz_to_csv.py
