name: tests

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up conda environment
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge
    - name: Install paraview
      run: |
        conda install paraview
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[tests]
    - name: Test with pytest
      run: |
        pytest -v tests
